#pragma once

namespace smpl {

	const unsigned int SHAPE_COEFFICIENTS = 10;
	const unsigned int POSE_COEFFICIENTS = 207;
	const unsigned int POSEDIRS_COUNT = 207;
	const unsigned int VERTEX_COUNT = 6890;
	const unsigned int FACE_COUNT = 13776;
	const unsigned int MAX_TRIANGLES_PER_VERTEX = 9;
	const unsigned int POSEDIRS_ELEMENTS_COUNT = 4278690;

	typedef
	enum _SKELETON_POSITION_INDEX
	{
		SKELETON_POSITION_HIP_CENTER = 0,
		SKELETON_POSITION_HIP_RIGHT = (SKELETON_POSITION_HIP_CENTER + 1),
		SKELETON_POSITION_HIP_LEFT = (SKELETON_POSITION_HIP_RIGHT + 1),
		SKELETON_POSITION_STOMACH = (SKELETON_POSITION_HIP_LEFT + 1),
		SKELETON_POSITION_KNEE_RIGHT = (SKELETON_POSITION_STOMACH + 1),
		SKELETON_POSITION_KNEE_LEFT = (SKELETON_POSITION_KNEE_RIGHT + 1),
		SKELETON_POSITION_BACKBONE = (SKELETON_POSITION_KNEE_LEFT + 1),
		SKELETON_POSITION_ANKLE_RIGHT = (SKELETON_POSITION_BACKBONE + 1),
		SKELETON_POSITION_ANKLE_LEFT = (SKELETON_POSITION_ANKLE_RIGHT + 1),
		SKELETON_POSITION_CHEST = (SKELETON_POSITION_ANKLE_LEFT + 1),
		SKELETON_POSITION_FOOT_RIGHT = (SKELETON_POSITION_CHEST + 1),
		SKELETON_POSITION_FOOT_LEFT = (SKELETON_POSITION_FOOT_RIGHT + 1),
		SKELETON_POSITION_SHOULDER_CENTER = (SKELETON_POSITION_FOOT_LEFT + 1),
		SKELETON_POSITION_PECK_RIGHT = (SKELETON_POSITION_SHOULDER_CENTER + 1),
		SKELETON_POSITION_PECK_LEFT = (SKELETON_POSITION_PECK_RIGHT + 1),
		SKELETON_POSITION_CHIN = (SKELETON_POSITION_PECK_LEFT + 1),
		SKELETON_POSITION_SHOULDER_RIGHT = (SKELETON_POSITION_CHIN + 1),
		SKELETON_POSITION_SHOULDER_LEFT = (SKELETON_POSITION_SHOULDER_RIGHT + 1),
		SKELETON_POSITION_ELBOW_RIGHT = (SKELETON_POSITION_SHOULDER_LEFT + 1),
		SKELETON_POSITION_ELBOW_LEFT = (SKELETON_POSITION_ELBOW_RIGHT + 1),
		SKELETON_POSITION_WRIST_RIGHT = (SKELETON_POSITION_ELBOW_LEFT + 1),
		SKELETON_POSITION_WRIST_LEFT = (SKELETON_POSITION_WRIST_RIGHT + 1),
		SKELETON_POSITION_HAND_RIGHT = (SKELETON_POSITION_WRIST_LEFT + 1),
		SKELETON_POSITION_HAND_LEFT = (SKELETON_POSITION_HAND_RIGHT + 1),
		SKELETON_POSITION_COUNT = (SKELETON_POSITION_HAND_LEFT + 1)
	} 	SKELETON_POSITION_INDEX;

	struct ShapeCoefficients 
	{
		float betas[SHAPE_COEFFICIENTS];
	};

	struct PoseCoefficients 
	{
		float thetas[POSE_COEFFICIENTS];
	};

	struct Vertex
	{
		float weight[4];
		int joint_idx[4];
		float pos[3];
		float nor[3];

		Vertex(float posx, float posy, float posz)
			: pos{ posx,posy,posz }, nor{ 0.f,0.f,0.f } {}
	};
}